# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1277cf142b96f52735a985a33a7080d043673e8c345411d41d57d57c7164a7755165d4dd9e811797e1b57f24bf912ae90b8a51db38118f5489c0c4f02afba17

test:
  secret_key_base: c0255dbd3a8f718a1b29bf0cf68b0ea561df2967e86813961b42b8dd0253ee7813e281f310fd482f45d792482238c1fb41c2622e7f3c3b7e7bd88daaec1b8fe3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
